[package]
name = "tuner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.0"
env_logger = "0.10.0"
log = "0.4.17"
realfft = "3.2.0"
ringbuf = "0.3.2"
rustfft = "6.1.0"
